proxy:
  title: ShinyProxy with Rhino
  logo-url: https://www.example.com/logo.png
  landing-page: /
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  port: 8080
  authentication: simple
  users:
  - name: user
    password: password
  docker:
      internal-networking: true
  specs:
  - id: rhino-app
    display-name: Rhino Shiny App
    description: App developed with Rhino framework
    container-cmd: ["R", "-e", "rhino::run_app('/srv/shiny-server/app')"]
    container-image: rhino-shiny-app
    access-groups: scientists

logging:
  file:
    shinyproxy.log
