version: '3.8'
services:
  trisk-api:
    image: registry.digitalocean.com/theia-1in1000-shinyapps/trisk_api:latest
    environment:
      POSTGRES_USERNAME: "${POSTGRES_USERNAME}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_HOST: "${POSTGRES_HOST}"
      POSTGRES_PORT: "${POSTGRES_PORT}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - "8000:8000"

  crispy-app:
    image: registry.digitalocean.com/theia-1in1000-shinyapps/crispy_app:latest
    environment:
      POSTGRES_USERNAME: "${POSTGRES_USERNAME}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_HOST: "${POSTGRES_HOST}"
      POSTGRES_PORT: "${POSTGRES_PORT}"
      POSTGRES_DB: "${POSTGRES_DB}"
      TRISK_API_SERVICE: http://trisk-api-service:8000
    depends_on:
      - trisk-api
    ports:
      - "6000:6000"

  shinyproxy-server:
    image: registry.digitalocean.com/theia-1in1000-shinyapps/shinyproxy:latest
    volumes:
      - ./application.yml:/opt/shinyproxy/application.yml
    ports:
      - "8080:8080"
    depends_on:
      - crispy-app
      - trisk-api

networks:
  default:
    driver: bridge
