version: '3.8'

services:
  shiny_app:
    build:
      context: ./path_to_shiny_app_directory
      dockerfile: Dockerfile_shiny # Name this according to your actual Dockerfile name for the Shiny app
    volumes:
      - ./path_to_shiny_app_directory:/srv/shiny-server
    environment:
      - CRISPY_APP_ENV=prod
    networks:
      - app_network

  r_api:
    build:
      context: ./path_to_r_api_directory
      dockerfile: Dockerfile_r_api # Name this according to your actual Dockerfile name for the R API
    volumes:
      - ./path_to_r_api_directory:/app
    environment:
      - POSTGRES_DB=NULL
      - POSTGRES_USERNAME=NULL
      - POSTGRES_PASSWORD=NULL
      - POSTGRES_HOST=shiny_app # Use the service name as hostname for inter-container communication
      - POSTGRES_PORT=NULL
      - S3_URL=NULL
      - S3_ACCESS_KEY=NULL
      - S3_SECRET_KEY=NULL
      - S3_BUCKET=NULL
      - S3_REGION=NULL
    ports:
      - "8080:8080" # Expose the R API on port 8080
    networks:
      - app_network

networks:
  app_network:
