version: '3.8'
services:
  trisk-api:
    image: registry.digitalocean.com/theia-1in1000-shinyapps/trisk_api:latest
    environment:
      POSTGRES_USERNAME: "your_username"
      POSTGRES_PASSWORD: "your_password"
      POSTGRES_HOST: "your_db_host"
      POSTGRES_PORT: "your_db_port"
      POSTGRES_DB: "your_db_name"
    ports:
      - "8000:8000"

  crispy-app:
    image: registry.digitalocean.com/theia-1in1000-shinyapps/crispy_app:latest
    environment:
      POSTGRES_USERNAME: "your_username"
      POSTGRES_PASSWORD: "your_password"
      POSTGRES_HOST: "your_db_host"
      POSTGRES_PORT: "your_db_port"
      POSTGRES_DB: "your_db_name"
    depends_on:
      - trisk-api
    ports:
      - "6000:6000"

  shinyproxy-server:
    image: registry.digitalocean.com/theia-1in1000-shinyapps/shinyproxy:latest
    volumes:
      - ./application.yml:/opt/shinyproxy/application.yml
    ports:
      - "8080:8080"
    depends_on:
      - crispy-app
      - trisk-api

networks:
  default:
    driver: bridge
