proxy:
  title: Shiny Proxy
  landing-page: /
  port: 8080
  authentication: simple
  admin-groups: admins
  users:
  - name: admin
    password: password
    groups: admins
  - name: user
    password: password
    groups: users
  # Kubernetes specific configuration
  container-backend: kubernetes
  kubernetes:
    url: https://kubernetes.default.svc
    namespace: shinyproxy # Specify the namespace here
    internal-networking: true
    # pod-wait-time: 60000
    image-pull-policy: Always
    image-pull-secret: theia-1in1000-shinyapps # CREATE MANUALLY IF NOT USING KUBERNETES ON DIGITALOCEAN
    # privileged: false # Keep containers unprivileged unless necessary
    # container-protocol: http # Default is suitable for most, switch to https if your app requires secure communication
    # port: 3838 # Default Shiny port, adjust if your app uses a different port
  # heartbeat-rate: 10000
  # heartbeat-timeout: 60000
  # # Load balancing configuration
  # container-wait-time: 30000
  specs:
    - id: crispy_app
      port: 5000 
      display-name: Crispy App
      description: "Climate stress test for Equities, Bonds&Loans"
      container-cmd: ["R", "-e", "shiny::runApp(host = \"0.0.0.0\", port = 5000)"]
      container-image: registry.digitalocean.com/theia-1in1000-shinyapps/crispy_app:latest
      access-groups: ["admins", "users"]
      env:
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: postgres_username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: postgres_password
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: postgres_host
        - name: POSTGRES_PORT
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: postgres_port
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: postgres_db      
      # container-memory-request: 500Mi
      # container-memory-limit: 1Gi
      # container-cpu-request: 500m
      # container-cpu-limit: 1

logging:
  file:
    name: shinyproxy.log






