proxy:
  title: Shiny Proxy
  logo-url: file:///etc/shinyproxy/logo.png
  landing-page: /
  port: 8080
  authentication: simple
  admin-groups: admins
  users:
  - name: admin
    password: password
    groups: admins
  - name: user
    password: password
    groups: users
  # Kubernetes specific configuration
  kubernetes:
    url: https://kubernetes.default.svc
    namespace: default
    internal-networking: true
    pod-wait-time: 60000
    image-pull-policy: Always
    image-pull-secret: digitalocean-registry-secret
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  # Load balancing configuration
  container-wait-time: 30000
  specs:
    - id: app1
      display-name: App 1
      description: "An example Shiny app"
      container-cmd: ["R", "-e", "rhino::app()"]
      container-image: registry.digitalocean.com/theia-1in1000-shinyapps/trisk_api:latest
      access-groups: ["users"]

logging:
  file:
    name: shinyproxy.log






