proxy:
  title: Shiny Proxy
  landing-page: /
  port: 8080
  authentication: simple
  admin-groups: admins
  users:
  - name: admin
    password: password
    groups: admins
  - name: user
    password: password
    groups: users
  # Kubernetes specific configuration
  container-backend: kubernetes
  kubernetes:
    url: https://kubernetes.default.svc
    namespace: shinyapps # Specify the namespace here
    internal-networking: true
    pod-wait-time: 60000
    image-pull-policy: Always
    image-pull-secret: theia-1in1000-shinyapps
    # privileged: false # Keep containers unprivileged unless necessary
    # container-protocol: http # Default is suitable for most, switch to https if your app requires secure communication
    # port: 3838 # Default Shiny port, adjust if your app uses a different port
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  # Load balancing configuration
  container-wait-time: 30000
  specs:
    - id: app1
      display-name: App 1
      description: "An example Shiny app"
      container-cmd: ["R", "-e", "rhino::app()"]
      container-image: registry.digitalocean.com/theia-1in1000-shinyapps/trisk_api:latest
      access-groups: ["admins", "users"]

logging:
  file:
    name: shinyproxy.log






