apiVersion: v1
kind: Secret
metadata:
  name: digitalocean-registry-secret
type: Opaque
data:
  docker-server: ${MY_REGISTRY_URL}
  docker-username: ${MY_REGISTRY_USERNAME}
  docker-password: ${MY_REGISTRY_PASSWORD}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shinyproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shinyproxy
  template:
    metadata:
      labels:
        app: shinyproxy
    spec:
      containers:
      - name: shinyproxy
        image: registry.digitalocean.com/theia-1in1000-shinyapps/shinyproxy:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: shinyproxy
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: shinyproxy
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shinyproxy-user
  namespace: shinyapps
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: shinyapps
  name: shinyproxy-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "pods/exec", "pods/portforward"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: shinyproxy-rolebinding
  namespace: shinyapps
subjects:
- kind: ServiceAccount
  name: shinyproxy-user
  namespace: shinyapps
roleRef:
  kind: Role
  name: shinyproxy-role
  apiGroup: rbac.authorization.k8s.io
