apiVersion: v1
kind: Secret
metadata:
  name: digitalocean-registry-secret
type: Opaque
data:
  docker-server: ${MY_REGISTRY_URL}
  docker-username: ${MY_REGISTRY_USERNAME}
  docker-password: ${MY_REGISTRY_PASSWORD}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shinyproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shinyproxy
  template:
    metadata:
      labels:
        app: shinyproxy
    spec:
      containers:
      - name: shinyproxy
        image: registry.digitalocean.com/theia-1in1000-shinyapps/shinyproxy:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: shinyproxy
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: shinyproxy
