apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
type: Opaque
data:
  s3_url: ${S3_URL}
  s3_access_key: ${S3_ACCESS_KEY}
  s3_secret_key: ${S3_SECRET_KEY}
  s3_bucket: ${S3_BUCKET}
  s3_region: ${S3_REGION}
---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  postgres_username: ${POSTGRES_USERNAME}
  postgres_password: ${POSTGRES_PASSWORD}
  postgres_host: ${POSTGRES_HOST}
  postgres_port: ${POSTGRES_PORT}
  postgres_db: ${POSTGRES_DB}
---  
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-domain
  namespace: knative-serving
data:
  143.244.207.98: ""
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: trisk-api
spec:
  template:
    metadata:
      name: trisk-api-service
      annotations:
        autoscaling.knative.dev/target: "1" # R is single threaded so 1 pod per API connection
    spec:
      containers:
        - image: registry.digitalocean.com/theia-1in1000-shinyapps/trisk_api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: ST_POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: postgres_username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: postgres_password
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: postgres_host
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: postgres_port
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: postgres_db
            - name: S3_URL
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: crispy_s3_url
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: crispy_s3_access_key
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: crispy_s3_secret_key
            - name: S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: crispy_s3_bucket
            - name: S3_REGION
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: crispy_s3_region

