apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: trisk-api
spec:
  template:
    metadata:
      name: trisk-api-service
      annotations:
        autoscaling.knative.dev/target: "1" # R is single threaded so 1 pod per API connection
    spec:
      containers:
        - image: registry.digitalocean.com/theia-1in1000-shinyapps/trisk_api:latest
          ports:
            - containerPort: 8080
          env:
            - name: ST_POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: postgres_username
            - name: ST_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: postgres_password
            - name: ST_POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: postgres_host
            - name: ST_POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: postgres_port
            - name: ST_POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: postgres_db

